# Common Traefik Helm values for both production and development
service:
  type: LoadBalancer

deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:1.31.1
      command: ["sh", "-c", "touch /data/acme.json && chmod 600 /data/acme.json"]
      volumeMounts:
        - name: traefik-acme
          mountPath: /data

persistence:
  enabled: true
  name: traefik-acme
  size: 128Mi
  path: /data

additionalArguments: []
  
ports:
  web:
    port: 8000
    expose: true
    exposedPort: 80
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    tls:
      enabled: true

providers:
  kubernetesCRD:
    enabled: true
    namespaces:
    - "traefik"
    - "shipkit-system"
  kubernetesIngress:
    enabled: false
