apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: shipkit-https-redirect
  namespace: traefik
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: shipkit-subdomain-filter
  namespace: traefik
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Host: "{{ req.Host }}"