apiVersion: v1
kind: Secret
metadata:
  name: traefik-acme
  namespace: traefik
  labels:
    app.kubernetes.io/managed-by: shipkit
    app.kubernetes.io/component: ingress-controller
    app.kubernetes.io/name: traefik
type: Opaque
stringData: {}
