type Deployment {
    id: ID!
    name: String!
    manifestYaml: String!
    createdAt: String!
}

input ServiceDefinitionDTO {
    serviceName: String!
    image: String!
    internalPort: Int
    subDomain: String
    sslEnabled: Boolean!
}

input CreateDeploymentDTO {
    name: String!
    services: [ServiceDefinitionDTO!]
}

input UpdateDeploymentDTO {
    name: String
    services: [ServiceDefinitionDTO!]
}

type ContainerStatus {
    name: String!
    state: String!
    readiness: String
    ports: [String!]!
}

type DeploymentStatus {
    uuid: String!
    state: String!
    message: String
    status: Int!
    containers: [ContainerStatus!]!
}

extend type Mutation {
    createDeployment(input: CreateDeploymentDTO!): Deployment!
    updateDeployment(id: ID!, input: UpdateDeploymentDTO!): Deployment!
    deleteDeployment(id: ID!): Boolean!
    startDeployment(id: ID!): Deployment!
    stopDeployment(id: ID!): Boolean!
}

extend type Query {
    deploymentStatus(id: ID!): DeploymentStatus!
    deployments: [Deployment!]!
} 