spring.application.name=shipkit-app

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/shipkit_dev}
spring.datasource.username=${DB_USERNAME:devuser}
spring.datasource.password=${DB_PASSWORD:devpass}

# Read .env files
spring.config.import=optional:file:.env[.properties]