apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/traefik
- ../../base/ingress
- ../../base

patches:
- path: traefik-patch.yaml
  target:
    kind: ConfigMap
    name: traefik-config

commonLabels:
  environment: development
