apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/traefik
- ../../base/ingress
- ../../base

patches:
- path: gateway-api-image-patch.yaml
  target:
    kind: Deployment
    name: gateway-api
- path: frontend-image-patch.yaml
  target:
    kind: Deployment
    name: shipkit-frontend
- path: k3s-control-image-patch.yaml
  target:
    kind: Deployment
    name: k3s-control

commonLabels:
  environment: development
