apiVersion: v1
kind: Secret
metadata:
  name: traefik-acme
  namespace: traefik
type: Opaque
stringData:
  TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_CASERVER: "https://acme-staging-v02.api.letsencrypt.org/directory"
