// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: proto/docker_control.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DockerControlService_StartCompose_FullMethodName  = "/docker_control.DockerControlService/StartCompose"
	DockerControlService_StopApp_FullMethodName       = "/docker_control.DockerControlService/StopApp"
	DockerControlService_RestartApp_FullMethodName    = "/docker_control.DockerControlService/RestartApp"
	DockerControlService_UpdateCompose_FullMethodName = "/docker_control.DockerControlService/UpdateCompose"
	DockerControlService_GetStatus_FullMethodName     = "/docker_control.DockerControlService/GetStatus"
)

// DockerControlServiceClient is the client API for DockerControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DockerControlService provides Docker Compose management operations
type DockerControlServiceClient interface {
	// StartCompose creates and starts containers from docker-compose.yml
	StartCompose(ctx context.Context, in *StartComposeRequest, opts ...grpc.CallOption) (*ActionResult, error)
	// StopApp stops all containers for the given UUID
	StopApp(ctx context.Context, in *StopAppRequest, opts ...grpc.CallOption) (*ActionResult, error)
	// RestartApp restarts all containers for the given UUID
	RestartApp(ctx context.Context, in *RestartAppRequest, opts ...grpc.CallOption) (*ActionResult, error)
	// UpdateCompose updates the docker-compose.yml and restarts containers
	UpdateCompose(ctx context.Context, in *UpdateComposeRequest, opts ...grpc.CallOption) (*ActionResult, error)
	// GetStatus returns the current status of containers for the given UUID
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*AppStatus, error)
}

type dockerControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDockerControlServiceClient(cc grpc.ClientConnInterface) DockerControlServiceClient {
	return &dockerControlServiceClient{cc}
}

func (c *dockerControlServiceClient) StartCompose(ctx context.Context, in *StartComposeRequest, opts ...grpc.CallOption) (*ActionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResult)
	err := c.cc.Invoke(ctx, DockerControlService_StartCompose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerControlServiceClient) StopApp(ctx context.Context, in *StopAppRequest, opts ...grpc.CallOption) (*ActionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResult)
	err := c.cc.Invoke(ctx, DockerControlService_StopApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerControlServiceClient) RestartApp(ctx context.Context, in *RestartAppRequest, opts ...grpc.CallOption) (*ActionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResult)
	err := c.cc.Invoke(ctx, DockerControlService_RestartApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerControlServiceClient) UpdateCompose(ctx context.Context, in *UpdateComposeRequest, opts ...grpc.CallOption) (*ActionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResult)
	err := c.cc.Invoke(ctx, DockerControlService_UpdateCompose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerControlServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*AppStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppStatus)
	err := c.cc.Invoke(ctx, DockerControlService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DockerControlServiceServer is the server API for DockerControlService service.
// All implementations must embed UnimplementedDockerControlServiceServer
// for forward compatibility.
//
// DockerControlService provides Docker Compose management operations
type DockerControlServiceServer interface {
	// StartCompose creates and starts containers from docker-compose.yml
	StartCompose(context.Context, *StartComposeRequest) (*ActionResult, error)
	// StopApp stops all containers for the given UUID
	StopApp(context.Context, *StopAppRequest) (*ActionResult, error)
	// RestartApp restarts all containers for the given UUID
	RestartApp(context.Context, *RestartAppRequest) (*ActionResult, error)
	// UpdateCompose updates the docker-compose.yml and restarts containers
	UpdateCompose(context.Context, *UpdateComposeRequest) (*ActionResult, error)
	// GetStatus returns the current status of containers for the given UUID
	GetStatus(context.Context, *GetStatusRequest) (*AppStatus, error)
	mustEmbedUnimplementedDockerControlServiceServer()
}

// UnimplementedDockerControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDockerControlServiceServer struct{}

func (UnimplementedDockerControlServiceServer) StartCompose(context.Context, *StartComposeRequest) (*ActionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartCompose not implemented")
}
func (UnimplementedDockerControlServiceServer) StopApp(context.Context, *StopAppRequest) (*ActionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopApp not implemented")
}
func (UnimplementedDockerControlServiceServer) RestartApp(context.Context, *RestartAppRequest) (*ActionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartApp not implemented")
}
func (UnimplementedDockerControlServiceServer) UpdateCompose(context.Context, *UpdateComposeRequest) (*ActionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCompose not implemented")
}
func (UnimplementedDockerControlServiceServer) GetStatus(context.Context, *GetStatusRequest) (*AppStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedDockerControlServiceServer) mustEmbedUnimplementedDockerControlServiceServer() {}
func (UnimplementedDockerControlServiceServer) testEmbeddedByValue()                              {}

// UnsafeDockerControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DockerControlServiceServer will
// result in compilation errors.
type UnsafeDockerControlServiceServer interface {
	mustEmbedUnimplementedDockerControlServiceServer()
}

func RegisterDockerControlServiceServer(s grpc.ServiceRegistrar, srv DockerControlServiceServer) {
	// If the following call pancis, it indicates UnimplementedDockerControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DockerControlService_ServiceDesc, srv)
}

func _DockerControlService_StartCompose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartComposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerControlServiceServer).StartCompose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerControlService_StartCompose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerControlServiceServer).StartCompose(ctx, req.(*StartComposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerControlService_StopApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerControlServiceServer).StopApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerControlService_StopApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerControlServiceServer).StopApp(ctx, req.(*StopAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerControlService_RestartApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerControlServiceServer).RestartApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerControlService_RestartApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerControlServiceServer).RestartApp(ctx, req.(*RestartAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerControlService_UpdateCompose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateComposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerControlServiceServer).UpdateCompose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerControlService_UpdateCompose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerControlServiceServer).UpdateCompose(ctx, req.(*UpdateComposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerControlService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerControlServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerControlService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerControlServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DockerControlService_ServiceDesc is the grpc.ServiceDesc for DockerControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DockerControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "docker_control.DockerControlService",
	HandlerType: (*DockerControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartCompose",
			Handler:    _DockerControlService_StartCompose_Handler,
		},
		{
			MethodName: "StopApp",
			Handler:    _DockerControlService_StopApp_Handler,
		},
		{
			MethodName: "RestartApp",
			Handler:    _DockerControlService_RestartApp_Handler,
		},
		{
			MethodName: "UpdateCompose",
			Handler:    _DockerControlService_UpdateCompose_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _DockerControlService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/docker_control.proto",
}
