package proto

import "google.golang.org/grpc"

// ActionResult is a placeholder matching the proto message.
type ActionResult struct {
	Status  int32
	Message string
	Details string
}

type ApplyRequest struct {
	Uuid         string
	ManifestYaml string
}

type DeleteRequest struct {
	Uuid string
}

type StatusRequest struct {
	Uuid string
}

type AppStatus struct {
	Uuid    string
	Status  int32
	Message string
}

// K3sControlServiceServer is the server API for K3sControlService service.
type K3sControlServiceServer interface {
	ApplyDeployment(*ApplyRequest) (*ActionResult, error)
	DeleteDeployment(*DeleteRequest) (*ActionResult, error)
	GetStatus(*StatusRequest) (*AppStatus, error)
}

// UnimplementedK3sControlServiceServer should be embedded to have forward compatible implementations.
type UnimplementedK3sControlServiceServer struct{}

func (UnimplementedK3sControlServiceServer) ApplyDeployment(*ApplyRequest) (*ActionResult, error) {
	return nil, nil
}
func (UnimplementedK3sControlServiceServer) DeleteDeployment(*DeleteRequest) (*ActionResult, error) {
	return nil, nil
}
func (UnimplementedK3sControlServiceServer) GetStatus(*StatusRequest) (*AppStatus, error) {
	return nil, nil
}

// RegisterK3sControlServiceServer is a stub; real implementation will be generated by protoc.
func RegisterK3sControlServiceServer(s *grpc.Server, srv K3sControlServiceServer) {}
