// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.29.4
// source: proto/k3s_control.proto

package k3s_control

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	K3SControlService_ApplyDeployment_FullMethodName  = "/k3s_control.K3sControlService/ApplyDeployment"
	K3SControlService_DeleteDeployment_FullMethodName = "/k3s_control.K3sControlService/DeleteDeployment"
	K3SControlService_GetStatus_FullMethodName        = "/k3s_control.K3sControlService/GetStatus"
)

// K3SControlServiceClient is the client API for K3SControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type K3SControlServiceClient interface {
	ApplyDeployment(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ActionResult, error)
	DeleteDeployment(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*ActionResult, error)
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*AppStatus, error)
}

type k3SControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewK3SControlServiceClient(cc grpc.ClientConnInterface) K3SControlServiceClient {
	return &k3SControlServiceClient{cc}
}

func (c *k3SControlServiceClient) ApplyDeployment(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ActionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResult)
	err := c.cc.Invoke(ctx, K3SControlService_ApplyDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k3SControlServiceClient) DeleteDeployment(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*ActionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResult)
	err := c.cc.Invoke(ctx, K3SControlService_DeleteDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k3SControlServiceClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*AppStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppStatus)
	err := c.cc.Invoke(ctx, K3SControlService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// K3SControlServiceServer is the server API for K3SControlService service.
// All implementations must embed UnimplementedK3SControlServiceServer
// for forward compatibility
type K3SControlServiceServer interface {
	ApplyDeployment(context.Context, *ApplyRequest) (*ActionResult, error)
	DeleteDeployment(context.Context, *DeleteRequest) (*ActionResult, error)
	GetStatus(context.Context, *StatusRequest) (*AppStatus, error)
	mustEmbedUnimplementedK3SControlServiceServer()
}

// UnimplementedK3SControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedK3SControlServiceServer struct {
}

func (UnimplementedK3SControlServiceServer) ApplyDeployment(context.Context, *ApplyRequest) (*ActionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyDeployment not implemented")
}
func (UnimplementedK3SControlServiceServer) DeleteDeployment(context.Context, *DeleteRequest) (*ActionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDeployment not implemented")
}
func (UnimplementedK3SControlServiceServer) GetStatus(context.Context, *StatusRequest) (*AppStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedK3SControlServiceServer) mustEmbedUnimplementedK3SControlServiceServer() {}

// UnsafeK3SControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to K3SControlServiceServer will
// result in compilation errors.
type UnsafeK3SControlServiceServer interface {
	mustEmbedUnimplementedK3SControlServiceServer()
}

func RegisterK3SControlServiceServer(s grpc.ServiceRegistrar, srv K3SControlServiceServer) {
	s.RegisterService(&K3SControlService_ServiceDesc, srv)
}

func _K3SControlService_ApplyDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K3SControlServiceServer).ApplyDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K3SControlService_ApplyDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K3SControlServiceServer).ApplyDeployment(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K3SControlService_DeleteDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K3SControlServiceServer).DeleteDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K3SControlService_DeleteDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K3SControlServiceServer).DeleteDeployment(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K3SControlService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K3SControlServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K3SControlService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K3SControlServiceServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// K3SControlService_ServiceDesc is the grpc.ServiceDesc for K3SControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var K3SControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "k3s_control.K3sControlService",
	HandlerType: (*K3SControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyDeployment",
			Handler:    _K3SControlService_ApplyDeployment_Handler,
		},
		{
			MethodName: "DeleteDeployment",
			Handler:    _K3SControlService_DeleteDeployment_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _K3SControlService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/k3s_control.proto",
}
