services:
  postgres:
    image: postgres:latest
    container_name: shipkit_gateaway_db
    environment:
      POSTGRES_DB: shipkit_gateaway
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"