resources:
  - ../../base
images:
  - name: ghcr.io/lon60/shipkit-frontend
    newName: ghcr.io/lon60/shipkit-frontend
    newTag: latest
  - name: ghcr.io/lon60/shipkit-gateway-api
    newName: ghcr.io/lon60/shipkit-gateway-api
    newTag: latest
  - name: ghcr.io/lon60/shipkit-k3s-control
    newName: ghcr.io/lon60/shipkit-k3s-control
    newTag: latest
